model_name: "Qwen/Qwen2-0.5B"
dataset_name: "data/"
batch_size: 2
lr: 0.00005  # Bu formatta olmalı
epochs: 3
quantize: false                    # 8-bit için true yapabilirsin
gradient_accumulation_steps: 4
max_seq_length: 1024
logging_steps: 50
save_strategy: "epoch"
output_dir: "outputs/sft"
